stages:
  - deploy-develop
  - build-develop
  - ops-develop
  - deploy-testing
  - build-testing
  - ops-testing
  # - deploy-master
  # - build-master
  # - ops-master

#开发环境>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>========
deploy-develop_job:
  stage: deploy-develop
  retry: 2
  when: always
  tags:
    - bujiang-develop
  only:
    - develop
  script:
    - bash deploy front yph-admin develop

build-develop_job:
  stage: build-develop
  tags:
    - bujiang-develop
  only:
    - develop
  script:
    - source /etc/profile
    - cd /home/data/develop/front/yph-admin
    - npm i
    - npm run build

ops-develop_job:
  stage: ops-develop
  tags:
    - bujiang-develop
  only:
    - develop
  script:
    - if [ ! -d "/home/html/yph-admin" ]; then mkdir /home/html/yph-admin; fi
    - rm -rf /home/html/yph-admin/*
    - cp -rf /home/data/develop/front/yph-admin/dist/* /home/html/yph-admin

#测试环境>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>=======
deploy-testing_job:
  stage: deploy-testing
  retry: 2
  when: always
  tags:
    - bujiang-testing
  only:
    - testing
  script:
    - bash deploy front yph-admin testing

build-testing_job:
  stage: build-testing
  tags:
    - bujiang-testing
  only:
    - testing
  script:
    - cd /home/data/testing/front/yph-admin
    - npm i
    - npm run build

ops-testing_job:
  stage: ops-testing
  tags:
    - bujiang-testing
  only:
    - testing
  script:
    - if [ ! -d "/home/html/yph-admin" ]; then mkdir /home/html/yph-admin; fi
    - rm -rf /home/html/yph-admin/*
    - cp -rf /home/data/testing/front/yph-admin/dist/* /home/html/yph-admin
    
#线上环境>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>========
# deploy-master_job:
#   stage: deploy-master
#   retry: 2
#   when: always
#   before_script:
#     - if [ -f "/data/wwwroot/master/front/yph-admin/package-lock.json" ]; then rm -f /data/wwwroot/master/front/yph-admin/package-lock.json; fi
#     - if [ -f "/data/wwwroot/master/front/yph-admin/.env.production" ]; then rm -f /data/wwwroot/master/front/yph-admin/.env.production; fi
#   tags:
#     - dahiti-web1
#   only:
#     - master
#   script:
#     - bash deploy front yph-admin master

# build-master_job:
#   stage: build-master
#   tags:
#     - dahiti-web1
#   only:
#     - master
#   script:
#     - cd /data/wwwroot/master/front/yph-admin
#     - npm i
#     - npm run build

# ops-master_job:
#   stage: ops-master
#   tags:
#     - dahiti-web1
#   only:
#     - master
#   script:
#     - if [ ! -d "/data/wwwroot/html/yph-admin" ]; then mkdir /data/wwwroot/html/yph-admin; fi
#     - rm -rf /data/wwwroot/html/yph-admin/*
#     - cp -rf /data/wwwroot/master/front/yph-admin/dist/* /data/wwwroot/html/yph-admin